---
- hosts: c7
  vars:
   http_port: 80

  tasks:
  - name: install the latest version of Apache
    yum: name=httpd state=latest
    yum: name=screen state=latest
    yum: name=mc state=latest
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - name: make sure everything is up to date
    yum: name=* state=latest
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
